# config parameters for lab data system.


projects:
    1: test
    2: test
    3: test
    4: TG neuron activation and sensitization and the involvement of astrocyte

system_path:
    root: '/content/drive/My Drive/EXPDATA'
    twophoton: '2P'
    electrophysiology: 'EP'
    surgery: 'SURG'

# list all the drug tested in your porjects and need to use when you update the experiment records.
drug_list: ['ACSF', 'AL8810', 'L-NAME', 'oxamate', 'L-AA', 'GAP19', 'TTX', 'BIBN', 'HET', 'DAB', 'Napro', 'FLCT', 'PPADS', 'Ozagrel', 'Levcro', 'soup', 'A10606120', 'Prob', 'TNP-ATP', 'saline', 'CBN4', 'SNP', 'GAP26', 'SC560', 'AL8810']
